services:
  user:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: "yarn start:dev user"

  product:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: "yarn start:dev product"

  payment:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: "yarn start:dev payment"

  shipping:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: "yarn start:dev shipping"

  media:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: "yarn start:dev media"

  order:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: "yarn start:dev order"

  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ecommerce
    volumes:
      - dbdata:/var/lib/potsgresql/dbdata
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - user
      - product
      - payment
      - shipping
      - media
      - order

volumes:
  dbdata:
